# Generated by Django 5.1.6 on 2025-03-02 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название новости')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='books/', verbose_name='Фото news')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('category', models.ManyToManyField(related_name='news_category', to='product.category')),
                ('tags', models.ManyToManyField(related_name='news_tag', to='product.tag')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
